apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave
  template:
    metadata:
      labels:
        app: wave
    spec:
      automountServiceAccountToken: false  # <-- désactive l'accès au service account si non nécessaire
      containers:
        - name: wave-container
          image: abdoulie/wave-image:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
