apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Added storageClassName to specify the storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wave-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Added storageClassName to specify the storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wave-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Added storageClassName to specify the storage class
