apiVersion: v1
kind: Service
metadata:
  name: wave-app
spec:
  selector:
    app: wave-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: wave-db
spec:
  selector:
    app: wave-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: wave-redis
spec:
  selector:
    app: wave-redis
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6379
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: wave-nginx
spec:
  selector:
    app: wave-nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer
