apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-app
  template:
    metadata:
      labels:
        app: wave-app
    spec:
      containers:
        - name: wave-app
          image: abdoulie/wave-image:latest
          workingDir: /var/www/wave
          envFrom:
            - configMapRef:
                name: wave-env
          volumeMounts:
            - name: wave-storage
              mountPath: /var/www/wave/storage
            - name: wave-cache
              mountPath: /var/www/wave/bootstrap/cache
      volumes:
        - name: wave-storage
          persistentVolumeClaim:
            claimName: wave-storage-pvc
        - name: wave-cache
          persistentVolumeClaim:
            claimName: wave-cache-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-db
  template:
    metadata:
      labels:
        app: wave-db
    spec:
      containers:
        - name: wave-db
          image: mysql:latest  # Utilisation de l'image MySQL officielle
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: wave-env
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: wave-env
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: wave-env
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: wave-env
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc  


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-redis
  template:
    metadata:
      labels:
        app: wave-redis
    spec:
      containers:
        - name: wave-redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-nginx
  template:
    metadata:
      labels:
        app: wave-nginx
    spec:
      containers:
        - name: wave-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: wave-app-dir
              mountPath: /var/www/wave
      volumes:
        - name: nginx-config
          configMap:
            name: wave-nginx-config
        - name: wave-app-dir
          hostPath:
            path: /home/abdoulie/wave-app-deploy
            type: Directory