# ----------------------------------------
# DEPLOYMENT : Laravel Application (wave-app)
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-app
  template:
    metadata:
      labels:
        app: wave-app
    spec:
      containers:
        - name: wave-app
          image: abdoulie/wave-image:v1.0.0  # ✅ Utilise une version fixe
          workingDir: /var/www/wave
          envFrom:
            - configMapRef:
                name: wave-env
          volumeMounts:
            - name: wave-storage
              mountPath: /var/www/wave/storage
            - name: wave-cache
              mountPath: /var/www/wave/bootstrap/cache
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: wave-storage
          persistentVolumeClaim:
            claimName: wave-storage-pvc
        - name: wave-cache
          persistentVolumeClaim:
            claimName: wave-cache-pvc

---

# ----------------------------------------
# DEPLOYMENT : MySQL Database (wave-db)
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-db
  template:
    metadata:
      labels:
        app: wave-db
    spec:
      containers:
        - name: wave-db
          image: mysql:9.3
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: wave-env
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: wave-env
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: wave-env
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: wave-env
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc

---

# ----------------------------------------
# DEPLOYMENT : Redis (wave-redis)
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-redis
  template:
    metadata:
      labels:
        app: wave-redis
    spec:
      containers:
        - name: wave-redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---

# ----------------------------------------
# DEPLOYMENT : NGINX Web Server (wave-nginx)
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-nginx
  template:
    metadata:
      labels:
        app: wave-nginx
    spec:
      containers:
        - name: wave-nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: wave-app-dir
              mountPath: /var/www/wave
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: nginx-config
          configMap:
            name: wave-nginx-config
        - name: wave-app-dir
          hostPath:
            path: /home/abdoulie/wave-app-deploy
            type: Directory
