apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wave-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wave-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

abdoulie@production:~/wave-app-deploy$ cat service.yml
apiVersion: v1
kind: Service
metadata:
  name: wave-app
spec:
  selector:
    app: wave-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000


---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: wave-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: wave-redis
spec:
  selector:
    app: wave-redis
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6379
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: wave-nginx
spec:
  selector:
    app: wave-nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer